[package]
name = "project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
secp256k1 = { version = "0.28.0", features = ["rand"] }

sha2 = "0.10.8"
hex = "0.4.3"